### ISSUE TITLE
Fazer um script em outra linguagem para retornar uma citação aleatória do JSON

### ISSUE THREAD

**Issue by WillianRod** [WillianRod/CitacoesAPI#1]
Crie uma script em qualquer linguagem que retorne uma das citações seus detalhes, como:
- Tema
- Autor
- Id
- Quote

As citações estão dentro do arquivo `citacoes.json`
Se possível, adicione também como implementar seu código no README.md

Happy Hacking

**Comment by SergioJrDev** [comment]
Opa, deixa comigo. Posso fazer usando Node.js?

**Comment by WillianRod** [comment]
Sure. Só coloca então dentro de uma diretório diferente, tipo `CitacoesAPI/node`

**Comment by maythiago** [comment]
Irei fazer em Go

**Comment by SergioJrDev** [comment]
@WillianRod fiz em Node e abri a PR, https://github.com/WillianRod/CitacoesAPI/pull/2

Ainda quero implementar mais testes unitários, mas subi só pra vc dar uma olhada.

Criei um readme.md com as instruções também

**Comment by WillianRod** [comment]
@SergioJrDev Sensacional. Obrigado pela pull :)

**Comment by WillianRod** [comment]
@maythiago Muito obrigado pela contribuição 😃
